---
#001-Example-Pipeline.yaml
name: Trivy Code Scan Example

on:
  workflow_dispatch:

jobs:
  capture:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Start Sysdig System Capture
      uses: gccloudone-aurora-collab/falco-actions/start@54d299d4c40de1ad6bf680fefbbfed1bc5b8f057
      with:
        mode: analyze
        sysdig-version: "sha256:c63ec30ce5db5b0d934343028031bba32b81cb7cb3f82e82d87b72c9b1694922"
        custom-rule-file: '${{ github.workspace }}/.github/falco/rules/002-Repo-CodeScan.yaml'

# BEGIN - Normal Pipeline Workload
    - name: Checkout Repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Run Trivy Scan Action
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
      with:
        version: "v0.69.3"
        severity: "CRITICAL,HIGH"
        ignore-unfixed: true
        scan-type: "fs"
        format: "sarif"
        output: "trivy-results.sarif"

    - name: Upload Trivy Report to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@9e907b5e64f6b83e7804b09294d44122997950d6 # v4.32.3
      with:
        sarif_file: trivy-results.sarif

# END - Normal Pipeline Workload

    - name: Stop Sysdig System Capture
      uses: gccloudone-aurora-collab/falco-actions/stop@54d299d4c40de1ad6bf680fefbbfed1bc5b8f057
      with:
        mode: analyze
        
  scan:
    needs: capture 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
    - name: Checkout Repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Analyze
      uses: gccloudone-aurora-collab/falco-actions/analyze@54d299d4c40de1ad6bf680fefbbfed1bc5b8f057
      env:
        SYSDIG_VERSION: 'sha256:c63ec30ce5db5b0d934343028031bba32b81cb7cb3f82e82d87b72c9b1694922'
      with:
        falco-version: 'sha256:ba05dfb209cc1c2e912ce116d230b5f59c4542e7286f05b663c499066d5d6a42'
        custom-rule-file: '${{ github.workspace }}/.github/falco/rules/002-Repo-CodeScan.yaml'

  # disabled for now      
  #repo-scan:
  #  needs: scan
  #  uses: ./.github/workflows/000-Scan-Analysis.yaml



